# Stage 1: Build dependencies
FROM node:18 AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
# Stage 2: Run on a lighter image
FROM node:18-slim

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules

COPY . .

ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "dev"]
